# Generated by Django 4.2.1 on 2023-05-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subscribers',
            new_name='subscriber',
        ),
    ]
