# Generated by Django 4.2.1 on 2023-05-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_rename_subscribers_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='issubscribed',
            field=models.BooleanField(default=True),
        ),
    ]
